spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/meetingsys?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null
  multipartResolver:

  mail:
    host: smtp.163.com
    port: 465
    username: NLrsylzjj@163.com
    password: 163shou16rr17
    properties: 
      mail:
        smtp:
          auth: true
          timeout: 75000
          socketFactory: 
            class: javax.net.ssl.SSLSocketFactory
server: 
  servlet: 
    path: /api
jsets:
  shiro:
    jwt-enabled: true
    jwt-secret-key: ofaffadfev1234567--090swctewst